### ISSUE TITLE
Incompatible with `astroid >=2.6.0`

### ISSUE THREAD

**Issue by treiher** [Parquery/pyicontract-lint#37]
Using `pyicontract-lint` with `astroid >=2.6.0` leads to the following error:

```Console
Traceback (most recent call last):
  File "venv/bin/pyicontract-lint", line 5, in <module>
    from icontract_lint.main import main
  File "venv/lib/python3.9/site-packages/icontract_lint/__init__.py", line 97, in <module>
    class _AstroidVisitor:
  File "venv/lib/python3.9/site-packages/icontract_lint/__init__.py", line 104, in _AstroidVisitor
    assert "generic" not in [cls.__class__.__name__ for cls in astroid.ALL_NODE_CLASSES]
AttributeError: module 'astroid' has no attribute 'ALL_NODE_CLASSES'
```

**Comment by mristin** [comment]
Thanks, @treiher! I'll try to have it fixed in the next few days.

**Comment by mristin** [comment]
Hi @treiher ,
Could you please check if the PR #38 fixes the issue on your side? It worked on my local machine.

**Comment by treiher** [comment]
I can confirm that PR #38 fixes the issue. Thanks!

**Comment by mristin** [comment]
@treiher any other issues or should I release a patch version?

**Comment by treiher** [comment]
I think it makes sense to release a patch version. I have not found any further issues.

**Comment by mristin** [comment]
Thanks for the feedback! The patch release, 2.1.3, has just been released.
