### ISSUE TITLE
Does not detect return None

### ISSUE THREAD

**Issue by erikrw** [Parquery/pyicontract-lint#47]
Hi, I'm new to pyicontract-lint so apologies if I misunderstand something. In general, I think I do have pyicontract-lint working. For example, I can get it to react with a "no-condition" error if I leave out a condition in @require().

But with this test program:

```
from icontract import ensure

@ensure(lambda result: len(result) > 0)
def func():
    pass
```

I expected a "post-result-none" error, but instead I get "No errors detected."

**Comment by mristin** [comment]
@erikrw thanks for reporting the issue! My schedule is packed right now, but I'll try to have a look at it mid-August.

**Comment by mristin** [comment]
@erikrw Thank you for the patience! I'm finally looking at the issues.

pyicontract-lint is a very limited tool: it simply looks into the type annotations (using astroid) and decides whether the contracts and the method signatures match. For this particular case, you should use a more sophisticated tool such as [crosshair] or [icontract-hypothesis].

[crosshair]: https://github.com/pschanely/crosshair
[icontract-hypothesis]: https://github.com/mristin/icontract-hypothesis
