### ISSUE TITLE
Does not detect (simple) violation of precondition

### ISSUE THREAD

**Issue by erikrw** [Parquery/pyicontract-lint#48]
Hello, pyicontract-lint reports "No errors detected." on this example which violates the precondition:

```
from icontract import require

@require(lambda x: x > 0)
def func(x: int):
    pass

func(0)
```

Is this a bug, or just outside the scope of pyicontract-lint? In case of the latter, perhaps the readme file should describe more explicitly the scope of pyicontract-lint?

**Comment by mristin** [comment]
@erikrw this is tightly related to #47. Please allow me to repeat the answer as it applies here as well:
    
> pyicontract-lint is a very limited tool: it simply looks into the type annotations (using astroid) and decides whether the contracts and the method signatures match. For this particular case, you should use a more sophisticated tool such as [crosshair] or [icontract-hypothesis].
    
[crosshair]: https://github.com/pschanely/crosshair
[icontract-hypothesis]: https://github.com/mristin/icontract-hypothesis
